#print('Hello World')
#print("hello world")
#print("Phyton ile ilk günüm!")
#print("Fonksiyon şu şekilde tanımlanır: print('ekrana yazdırılacak yazı')")
#print("Merhaba Dünya\nMerhaba Dünya\nMerhaba Dünya\n")
#print("Merhaba Dünya")
#print("Merhaba Dünya")
#print("Merhaba Dünya")
#print("Merhaba"+" "+"Şahin")
#print("Merhaba"+"Şahin")
#print("Merhaba"+"Şahin")
#print(input("Merhaba, Adın Nedir?"))
#print("Merhaba " + input("Mehaba,Adın Nedir?") + "!")
#print(len(input("Merhaba, Adın Nedir?")))
#name = input("Merhaba Adın Nedir?")
#print(name)
#name = "Şahin"
#print(name)
#name = "Taşın"
#print(name)
#print(len(input("Merhaba, Adın Nedir?")))
#isim = input("Merhaba, Adın Nedir?")
#uzunluk = len(isim)
#print(uzunluk)
#Sayi1 = input("1nci Sayıyı Giriniz: ")
#Sayi2 = input("2nci Sayıyı Giriniz: ")
#Sayi3 = Sayi1
#Sayi1 = Sayi2
#Sayi2 = Sayi3
#print("Sayı1 : " + Sayi1)
#print("Sayı2 : " + Sayi2)
#print(len(str(1234567890)))
#print("Merhaba"[0])
# print(123 + 456)
#print(123_456_789)
#print(3.12345)
#print(True)
#print(False)
# isimUzunluk = len(input("Merhaba, Adın Ne?"))
# isimUzunluk_Str = str(isimUzunluk)
# print("İsminde " + isimUzunluk_Str + " karakter var.")
# f1 = float(1.322)
# print(type(f1))
# intt = int(232)
# print(type(intt))
# st = str(123123)
# print(type(st))
# print(100 + float(15.23))
# print(str(122) +str(324))
# ikihanelisayi = str(input("İki haneli bir sayı giriniz!"))
# toplam = int(ikihanelisayi[0]) + int(ikihanelisayi[1])
# print("Toplam: " + str(toplam))